version: '3.9'

services:
  backend:
    image: ${ECR_URL}/${ECR_REPO}:backend
    ports:
      - "8000:8000"
    networks:
      - recsys-net

  frontend:
    image: ${ECR_URL}/${ECR_REPO}:frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - recsys-net

networks:
  recsys-net:
