
services:
  backend:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: be-recsys
    ports:
      - "8000:8000"
    networks:
      - recsys-net

  frontend:
    build:
      context: .
      dockerfile: ./streamlit_app/Dockerfile
    container_name: fe-recsys
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - recsys-net
networks:
  recsys-net:
