name: "CD Build"

on:
  workflow_run:
    workflow: ["CI Build"]
      types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
        - name: Build project
          uses: actions/checkout@v4

        - name: Setup python
          uses: actions/setup-python@v5
          with: 
            python-version: '3.10'

        - name: Install dependencies
          run: pip install -r requirements.txt

        - name: Compose docker containers
          run: docker compose up

        
