name: "CD Build"

on:
  workflow_run:
    workflows: ["CI Build"]
    branches: [main]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  ECR_AUTH_URL: ${{ secrets.ECR_AUTH_URI }}
  ECR_URL: ${{ secrets.ECR_URL }}
  ECR_REPO: ${{ secrets.ECR_REPO }}

jobs:
  build-and-push-ecr-image:
    name: Continuous Delivery
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
      
    steps:
      - name: Build project
        uses: actions/checkout@v4
        
      - name: Installing utilities and updating AWS CLI 
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Configuring AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:  ${{ secrets.AWS_LOGIN_ACCESS_ID}}
          aws-secret-access-key: ${{ secrets.AWS_LOGIN_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION}}
    
      
      - name: Login to Amazon ECR and create repo if missing
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_AUTH_URL }}
          if ! aws ecr-public describe-repositories --repository-names $ECR_REPO --region us-east-1 > /dev/null 2>&1; then
            echo "Repository $ECR_REPO does not exist. Creating..."
            aws ecr-public create-repository --repository-name $ECR_REPO --region us-east-1
          else
            echo "Repository $ECR_REPO already exists. Skipping creation."
          fi

        # Backend Image

      - name: Build, tag, and push backend image
        run: |
           docker build -t $ECR_URL/$ECR_REPO:backend -f api/Dockerfile .
           docker push $ECR_URL/$ECR_REPO:backend
        # Frontend Image

      - name: Build, tag, and push frontend image
        run: |
          docker build -t $ECR_URL/$ECR_REPO:frontend -f streamlit_app/Dockerfile .
          docker push $ECR_URL/$ECR_REPO:frontend
      


  continuous-deployment:
    name: Continuous Deployment
    needs: build-and-push-ecr-image
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credientials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:  ${{ secrets.AWS_LOGIN_ACCESS_ID}}
          aws-secret-access-key: ${{ secrets.AWS_LOGIN_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Login into ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Generate .env file for Docker Compose
        run: |
          echo "ECR_REPO=${{ secrets.ECR_REPO }}" > .env
          echo "ECR_URL=${{ secrets.ECR_URL }}" >> .env

      - name: Pulling Docker images
        env:
          ECR_URL: ${{ secrets.ECR_URL }}
          ECR_REPO: ${{ secrets.ECR_REPO }}
        run: |
          # Removing old images to avoid unnessacary disk usage on EC2
          sudo docker system prune -af
          sudo docker compose pull
          sudo docker compose up -d