name: "CI Build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    #container: python3.10-slim
    steps:
        - name: Build project
          uses: actions/checkout@v4

        - name: Setup python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
         # Caching pip files to avoid redundant installation of packages
        - name: Cache pip
          uses: actions/cache@v3
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashfiles('**/requirements.txt')}}
            restore-keys: |
              ${{ runner.os }}-pip-

        - name: Install Dependencies
          run: pip install -r requirements.txt
        
        - name: Run unit tests
          run: |
            echo "Running unit tests for logic, utils, routes(fastapi) and streamlit_app"
            pytest -vv tests
        - run: echo "Unit testing completed."